-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- Generated by Quartus II Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition
-- Created on Mon Dec 01 15:35:48 2025

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY maq_barrido IS
    PORT (
        reset : IN STD_LOGIC := '0';
        clock : IN STD_LOGIC;
        C1 : IN STD_LOGIC := '0';
        C2 : IN STD_LOGIC := '0';
        C3 : IN STD_LOGIC := '0';
        C4 : IN STD_LOGIC := '0';
        F1 : OUT STD_LOGIC;
        F2 : OUT STD_LOGIC;
        F3 : OUT STD_LOGIC;
        F4 : OUT STD_LOGIC
    );
END maq_barrido;

ARCHITECTURE BEHAVIOR OF maq_barrido IS
    TYPE type_fstate IS (fl1,fl2,fl3,fl4,b1,b3,b2,b4);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,C1,C2,C3,C4)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= b1;
            F1 <= '0';
            F2 <= '0';
            F3 <= '0';
            F4 <= '0';
        ELSE
            F1 <= '0';
            F2 <= '0';
            F3 <= '0';
            F4 <= '0';
            CASE fstate IS
                WHEN fl1 =>
                    IF (((((C1 = C1) OR (C2 = C2)) OR (C3 = C3)) OR (C4 = C4))) THEN
                        reg_fstate <= fl1;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= fl1;
                    END IF;

                    F4 <= '0';

                    F3 <= '0';

                    F2 <= '0';

                    F1 <= '1';
                WHEN fl2 =>
                    IF (((((C1 = C1) OR (C2 = C2)) OR (C3 = C3)) OR (C4 = C4))) THEN
                        reg_fstate <= fl2;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= fl2;
                    END IF;

                    F4 <= '0';

                    F3 <= '0';

                    F2 <= '1';

                    F1 <= '0';
                WHEN fl3 =>
                    IF (((((C1 = C1) OR (C2 = C2)) OR (C3 = C3)) OR (C4 = C4))) THEN
                        reg_fstate <= fl3;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= fl3;
                    END IF;

                    F4 <= '0';

                    F3 <= '1';

                    F2 <= '0';

                    F1 <= '0';
                WHEN fl4 =>
                    IF (((((C1 = C1) OR (C2 = C2)) OR (C3 = C3)) OR (C4 = C4))) THEN
                        reg_fstate <= fl4;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= fl4;
                    END IF;

                    F4 <= '1';

                    F3 <= '0';

                    F2 <= '0';

                    F1 <= '0';
                WHEN b1 =>
                    IF (((((C1 = '0') AND (C2 = '0')) AND (C3 = '0')) AND (C4 = '0'))) THEN
                        reg_fstate <= b2;
                    ELSIF (((((C1 = '1') OR (C2 = '1')) OR (C3 = '1')) OR (C4 = '1'))) THEN
                        reg_fstate <= fl1;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= b1;
                    END IF;

                    F4 <= '0';

                    F3 <= '0';

                    F2 <= '0';

                    F1 <= '1';
                WHEN b3 =>
                    IF (((((C1 = '0') AND (C2 = '0')) AND (C3 = '0')) AND (C4 = '0'))) THEN
                        reg_fstate <= b4;
                    ELSIF (((((C1 = '1') OR (C2 = '1')) OR (C3 = '1')) OR (C4 = '1'))) THEN
                        reg_fstate <= fl3;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= b3;
                    END IF;

                    F4 <= '0';

                    F3 <= '1';

                    F2 <= '0';

                    F1 <= '0';
                WHEN b2 =>
                    IF (((((C1 = '0') AND (C2 = '0')) AND (C3 = '0')) AND (C4 = '0'))) THEN
                        reg_fstate <= b3;
                    ELSIF (((((C1 = '1') OR (C2 = '1')) OR (C3 = '1')) OR (C4 = '1'))) THEN
                        reg_fstate <= fl2;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= b2;
                    END IF;

                    F4 <= '0';

                    F3 <= '0';

                    F2 <= '1';

                    F1 <= '0';
                WHEN b4 =>
                    IF (((((C1 = '0') AND (C2 = '0')) AND (C3 = '0')) AND (C4 = '0'))) THEN
                        reg_fstate <= b1;
                    ELSIF (((((C1 = '1') OR (C2 = '1')) OR (C3 = '1')) OR (C4 = '1'))) THEN
                        reg_fstate <= fl4;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= b4;
                    END IF;

                    F4 <= '1';

                    F3 <= '0';

                    F2 <= '0';

                    F1 <= '0';
                WHEN OTHERS => 
                    F1 <= 'X';
                    F2 <= 'X';
                    F3 <= 'X';
                    F4 <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
