-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- Generated by Quartus II Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition
-- Created on Tue Dec 09 18:06:36 2025

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY maquina2 IS
    PORT (
        reset : IN STD_LOGIC := '0';
        clock : IN STD_LOGIC;
        modo_JvJ : IN STD_LOGIC := '0';
        modo_JvM : IN STD_LOGIC := '0';
        MV : IN STD_LOGIC := '0';
        V_J1 : IN STD_LOGIC := '0';
        V_J2 : IN STD_LOGIC := '0';
        EMPATE : IN STD_LOGIC := '0';
        EMPATE3 : IN STD_LOGIC := '0';
        VICTORIA13 : IN STD_LOGIC := '0';
        VICTORIA23 : IN STD_LOGIC := '0';
        modo : OUT STD_LOGIC;
        TURNO : OUT STD_LOGIC;
        INICIO : OUT STD_LOGIC;
        VICTORIA_RONDA : OUT STD_LOGIC;
        EMPATE_RONDA : OUT STD_LOGIC;
        limpiar_tablero : OUT STD_LOGIC;
        VICTORIA_FINAL0 : OUT STD_LOGIC;
        VICTORIA_FINAL1 : OUT STD_LOGIC;
        resetcontadores : OUT STD_LOGIC
    );
END maquina2;

ARCHITECTURE BEHAVIOR OF maquina2 IS
    TYPE type_fstate IS (SeC,TurnoJ1,TurnoJ2,VJ1,VE,VJ2,CE,CJ1,CJ2);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,modo_JvJ,modo_JvM,MV,V_J1,V_J2,EMPATE,EMPATE3,VICTORIA13,VICTORIA23)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= SeC;
            modo <= '0';
            TURNO <= '0';
            INICIO <= '0';
            VICTORIA_RONDA <= '0';
            EMPATE_RONDA <= '0';
            limpiar_tablero <= '0';
            VICTORIA_FINAL0 <= '0';
            VICTORIA_FINAL1 <= '0';
            resetcontadores <= '0';
        ELSE
            modo <= '0';
            TURNO <= '0';
            INICIO <= '0';
            VICTORIA_RONDA <= '0';
            EMPATE_RONDA <= '0';
            limpiar_tablero <= '0';
            VICTORIA_FINAL0 <= '0';
            VICTORIA_FINAL1 <= '0';
            resetcontadores <= '0';
            CASE fstate IS
                WHEN SeC =>
                    IF (((modo_JvJ = '0') AND (modo_JvM = '0'))) THEN
                        reg_fstate <= SeC;
                    ELSIF ((modo_JvJ = '1')) THEN
                        reg_fstate <= TurnoJ1;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= SeC;
                    END IF;

                    resetcontadores <= '1';

                    VICTORIA_FINAL1 <= '0';

                    VICTORIA_FINAL0 <= '0';

                    limpiar_tablero <= '0';

                    EMPATE_RONDA <= '0';

                    VICTORIA_RONDA <= '0';

                    INICIO <= '0';

                    TURNO <= '0';

                    modo <= '0';
                WHEN TurnoJ1 =>
                    IF ((((MV = '1') AND (EMPATE = '0')) AND (V_J2 = '0'))) THEN
                        reg_fstate <= TurnoJ2;
                    ELSIF ((((V_J2 = '1') AND (EMPATE = '0')) AND (MV = '0'))) THEN
                        reg_fstate <= CJ2;
                    ELSIF ((((EMPATE = '1') AND (MV = '0')) AND (V_J2 = '0'))) THEN
                        reg_fstate <= CE;
                    ELSIF (((((((V_J2 = '0') AND (EMPATE = '0')) AND (MV = '0')) OR (((V_J2 = '0') AND (EMPATE = '1')) AND (MV = '1'))) OR (((V_J2 = '1') AND (EMPATE = '0')) AND (MV = '1'))) OR ((V_J2 = '1') AND (EMPATE = '1')))) THEN
                        reg_fstate <= TurnoJ1;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= TurnoJ1;
                    END IF;

                    resetcontadores <= '0';

                    VICTORIA_FINAL1 <= '0';

                    VICTORIA_FINAL0 <= '0';

                    limpiar_tablero <= '0';

                    EMPATE_RONDA <= '0';

                    VICTORIA_RONDA <= '0';

                    INICIO <= '1';

                    TURNO <= '1';

                    modo <= '0';
                WHEN TurnoJ2 =>
                    IF ((((V_J1 = '1') AND (MV = '0')) AND (EMPATE = '0'))) THEN
                        reg_fstate <= CJ1;
                    ELSIF ((((MV = '1') AND (EMPATE = '0')) AND (V_J1 = '0'))) THEN
                        reg_fstate <= TurnoJ1;
                    ELSIF ((((EMPATE = '1') AND (MV = '0')) AND (V_J1 = '0'))) THEN
                        reg_fstate <= CE;
                    ELSIF ((((((((V_J1 = '0') AND (EMPATE = '0')) AND (MV = '0')) OR (((V_J1 = '0') AND (EMPATE = '0')) AND (MV = '0'))) OR (((V_J1 = '0') AND (EMPATE = '1')) AND (MV = '1'))) OR (((V_J1 = '1') AND (EMPATE = '0')) AND (MV = '1'))) OR ((V_J1 = '1') AND (EMPATE = '1')))) THEN
                        reg_fstate <= TurnoJ2;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= TurnoJ2;
                    END IF;

                    resetcontadores <= '0';

                    VICTORIA_FINAL1 <= '0';

                    VICTORIA_FINAL0 <= '0';

                    limpiar_tablero <= '0';

                    EMPATE_RONDA <= '0';

                    VICTORIA_RONDA <= '0';

                    INICIO <= '1';

                    TURNO <= '0';

                    modo <= '0';
                WHEN VJ1 =>
                    reg_fstate <= VJ1;

                    resetcontadores <= '0';

                    VICTORIA_FINAL1 <= '0';

                    VICTORIA_FINAL0 <= '1';

                    limpiar_tablero <= '0';

                    EMPATE_RONDA <= '0';

                    VICTORIA_RONDA <= '0';

                    INICIO <= '1';

                    TURNO <= '0';

                    modo <= '0';
                WHEN VE =>
                    reg_fstate <= VE;

                    resetcontadores <= '0';

                    VICTORIA_FINAL1 <= '1';

                    VICTORIA_FINAL0 <= '1';

                    limpiar_tablero <= '0';

                    EMPATE_RONDA <= '0';

                    VICTORIA_RONDA <= '0';

                    INICIO <= '0';

                    TURNO <= '0';

                    modo <= '0';
                WHEN VJ2 =>
                    reg_fstate <= VJ2;

                    resetcontadores <= '0';

                    VICTORIA_FINAL1 <= '1';

                    VICTORIA_FINAL0 <= '0';

                    limpiar_tablero <= '0';

                    EMPATE_RONDA <= '0';

                    VICTORIA_RONDA <= '0';

                    INICIO <= '1';

                    TURNO <= '0';

                    modo <= '0';
                WHEN CE =>
                    IF ((((VICTORIA23 = '0') AND (VICTORIA13 = '0')) AND (EMPATE3 = '0'))) THEN
                        reg_fstate <= TurnoJ1;
                    ELSIF ((((VICTORIA23 = '0') AND (VICTORIA13 = '0')) AND (EMPATE3 = '1'))) THEN
                        reg_fstate <= VE;
                    ELSIF ((((VICTORIA23 = '0') AND (VICTORIA13 = '1')) AND (EMPATE3 = '0'))) THEN
                        reg_fstate <= VJ1;
                    ELSIF ((((VICTORIA23 = '1') AND (VICTORIA13 = '0')) AND (EMPATE3 = '0'))) THEN
                        reg_fstate <= VJ2;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= CE;
                    END IF;

                    resetcontadores <= '0';

                    VICTORIA_FINAL1 <= '0';

                    VICTORIA_FINAL0 <= '0';

                    limpiar_tablero <= '1';

                    EMPATE_RONDA <= '1';

                    VICTORIA_RONDA <= '0';

                    INICIO <= '1';

                    TURNO <= '0';

                    modo <= '0';
                WHEN CJ1 =>
                    IF ((((VICTORIA13 = '0') AND (VICTORIA23 = '0')) AND (EMPATE3 = '0'))) THEN
                        reg_fstate <= TurnoJ1;
                    ELSIF ((((VICTORIA23 = '0') AND (VICTORIA13 = '1')) AND (EMPATE3 = '0'))) THEN
                        reg_fstate <= VJ1;
                    ELSIF ((((VICTORIA23 = '1') AND (VICTORIA13 = '0')) AND (EMPATE3 = '0'))) THEN
                        reg_fstate <= VJ2;
                    ELSIF ((((VICTORIA23 = '0') AND (VICTORIA13 = '0')) AND (EMPATE3 = '1'))) THEN
                        reg_fstate <= VE;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= CJ1;
                    END IF;

                    resetcontadores <= '0';

                    VICTORIA_FINAL1 <= '0';

                    VICTORIA_FINAL0 <= '0';

                    limpiar_tablero <= '1';

                    EMPATE_RONDA <= '0';

                    VICTORIA_RONDA <= '1';

                    INICIO <= '1';

                    TURNO <= '1';

                    modo <= '0';
                WHEN CJ2 =>
                    IF ((((VICTORIA23 = '1') AND (VICTORIA13 = '0')) AND (EMPATE3 = '0'))) THEN
                        reg_fstate <= VJ2;
                    ELSIF ((((VICTORIA23 = '0') AND (VICTORIA13 = '0')) AND (EMPATE3 = '0'))) THEN
                        reg_fstate <= TurnoJ2;
                    ELSIF ((((VICTORIA23 = '0') AND (VICTORIA13 = '1')) AND (EMPATE3 = '0'))) THEN
                        reg_fstate <= VJ1;
                    ELSIF ((((VICTORIA23 = '0') AND (VICTORIA13 = '0')) AND (EMPATE3 = '1'))) THEN
                        reg_fstate <= VE;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= CJ2;
                    END IF;

                    resetcontadores <= '0';

                    VICTORIA_FINAL1 <= '0';

                    VICTORIA_FINAL0 <= '0';

                    limpiar_tablero <= '1';

                    EMPATE_RONDA <= '0';

                    VICTORIA_RONDA <= '1';

                    INICIO <= '1';

                    TURNO <= '0';

                    modo <= '0';
                WHEN OTHERS => 
                    modo <= 'X';
                    TURNO <= 'X';
                    INICIO <= 'X';
                    VICTORIA_RONDA <= 'X';
                    EMPATE_RONDA <= 'X';
                    limpiar_tablero <= 'X';
                    VICTORIA_FINAL0 <= 'X';
                    VICTORIA_FINAL1 <= 'X';
                    resetcontadores <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
