-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- Generated by Quartus II Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition
-- Created on Wed Dec 03 10:12:37 2025

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY SM1 IS
    PORT (
        reset : IN STD_LOGIC := '0';
        clock : IN STD_LOGIC;
        X : IN STD_LOGIC := '0';
        t : IN STD_LOGIC := '0';
        bot : OUT STD_LOGIC;
        ic : OUT STD_LOGIC;
        estable : OUT STD_LOGIC
    );
END SM1;

ARCHITECTURE BEHAVIOR OF SM1 IS
    TYPE type_fstate IS (A,D,C,B);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,X,t)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= A;
            bot <= '0';
            ic <= '0';
            estable <= '0';
        ELSE
            bot <= '0';
            ic <= '0';
            estable <= '0';
            CASE fstate IS
                WHEN A =>
                    IF ((X = '0')) THEN
                        reg_fstate <= A;
                    ELSIF ((X = '1')) THEN
                        reg_fstate <= B;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= A;
                    END IF;

                    ic <= '0';

                    estable <= '0';

                    bot <= '0';
                WHEN D =>
                    IF ((t = '0')) THEN
                        reg_fstate <= D;
                    ELSIF (((X = '1') AND (t = '1'))) THEN
                        reg_fstate <= C;
                    ELSIF (((t = '1') AND (X = '0'))) THEN
                        reg_fstate <= A;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= D;
                    END IF;

                    ic <= '1';

                    estable <= '0';

                    bot <= '1';
                WHEN C =>
                    IF ((X = '1')) THEN
                        reg_fstate <= C;
                    ELSIF ((X = '0')) THEN
                        reg_fstate <= D;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= C;
                    END IF;

                    ic <= '0';

                    estable <= '1';

                    bot <= '1';
                WHEN B =>
                    IF (((t = '1') AND (X = '1'))) THEN
                        reg_fstate <= C;
                    ELSIF (((t = '1') AND (X = '0'))) THEN
                        reg_fstate <= A;
                    ELSIF ((t = '0')) THEN
                        reg_fstate <= B;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= B;
                    END IF;

                    ic <= '1';

                    estable <= '0';

                    bot <= '0';
                WHEN OTHERS => 
                    bot <= 'X';
                    ic <= 'X';
                    estable <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
